# phrases_list.py

PHRASES = [
    "Ir por una taza de café",
    "Jugar dos partidas de Fortnite",
    "Enviar un fax a Maduro",
    "Escribir en tu diario personal",
    "Retocar tu maquillaje",
    "Caminar dos cuadras y volver",
    "Jugar un par de partidas de DBD",
    "Ver una película 'masculina' como Titanic",
    "Ir a comer un helado",
    "Leer tu libro favorito",
    "Darle un beso a la persona más cercana",
    "Comer una hamburguesa vegana",
    "Buscar en Google cómo hacer del número dos correctamente",
    "Preparar una parrillada con todo",
    "Escribir todas las groserías conocidas en un papel",
    "Colocar un rollo de papel nuevo en el baño",
    "Escribir tu carta a Santa Claus",
    "Participar en la encuesta para ilegalizar el reguetón",
    "Regar las margaritas del jardín",
    "Promulgar leyes antiveganos",
    "Redactar un poema dedicado a la persona más cercana",
    "Buscar evidencia de la existencia del monstruo del lago Ness",
    "Dar una vuelta al mundo",
    "Meditar con monjes tibetanos sobre el significado de la vida",
    "Infiltrarte en la comunidad vegana",
    "Dar clic en 'me gusta' en una publicación de 'iPhone es mejor que Android'",
    "Felicidades, fuiste adoptado por Elon Musk",
    "Hacer un maratón de películas de Star Wars",
    "Se ha colocado en tu perfil de Facebook que eres fan de Justin Bieber",
    "Ir a comprar comida china y recibir un pan extra gratis",
    "Felicidades, eres propietario de una casa antigua y has ganado un viaje al pasado",
    "Aprender a hablar con las palomas del parque",
    "Inscribirte en un curso para convertirte en astronauta doméstico",
    "Tratar de mover objetos con la mente durante 10 minutos",
    "Hacer tu mejor intento de baile de robot frente al espejo",
    "Enviar una carta formal al WiFi pidiéndole más velocidad",
    "Ponerle nombre a cada uno de tus calcetines",
    "Convencer a tu mascota de que eres su líder espiritual",
    "Mirar fijamente una pared hasta que sospeche algo",
    "Intentar recordar dónde dejaste tus sueños de la infancia",
    "Preparar un jugo de agua",
    "Pedirle perdón a la planta que olvidaste regar hace dos días",
    "Hacer una lista de cosas por hacer y no hacer ninguna",
    "Sentarte en el piso para sentirte más profundo y misterioso",
    "Mandarte un mensaje a ti mismo diciendo 'hola bb'",
    "Revisar el refrigerador por décima vez aunque ya sabes que no hay nada",
    "Intentar pronunciar la palabra 'otorrinolaringólogo' sin fallar",
    "Mirar tutoriales de cómo ser feliz en 5 minutos",
    "Preguntarle a tu reflejo si está bien",
    "Suspirar dramáticamente para generar atención",
    "Intentar recordar el nombre del actor ese que sale en la película esa",
    "Jugar piedra, papel o tijeras contigo mismo (y perder)",
    "Practicar tu firma por si un día eres famoso",
    "Hacer una llamada imaginaria a Jeff Bezos",
    "Jugar a que eres chef profesional preparando un sándwich",
    "Decir 'voy a limpiar' y luego no limpiar nada",
    "Buscar tu nombre en Google solo para ver si ya eres famoso",
    "Escribir un discurso de victoria por si ganas un premio que no existe",
    "Guardar la tapa de un yogurt para 'algo importante'",
    "Pensar en hacer ejercicio y cansarte solo de pensarlo",
    "Cantarle una serenata a la luna sin razón alguna",
]
